# GoFrame CLI tool configuration.
gfcli:
  gen:
    dao:
      - link: "pgsql:neondb_owner:npg_OmQKRewY59HE@tcp(ep-shy-wave-aiwsav8s-pooler.c-4.us-east-1.aws.neon.tech:5432)/neondb?sslmode=require&channelBinding=require"
        tables: "users,quizzes,questions,answer_options,quiz_sessions,session_participants,user_answers,leaderboard_snapshots"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true